# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

**Ejercicios** /
**Objetivos de la sesión:**

Utilizar diferentes tipos de arreglos unidimensionales para almacenar datos según los requerimientos  solicitados

Utilizar diferentes tipos de arreglos bidimensionales para almacenar datos según los requerimientos  solicitados.

Utilizar GitHub para el respaldo de los códigos desarrollados en Python.

Crear diferentes funciones definidas por el usuario, para dar respuesta a los requerimientos del caso.
"""

import numpy as np

#Ejercicio 1:
arreglo_uni = np.random.randint(0, 101, size=10)

ingrese_numero = int(input("ingrese un número:" ))
print("")
print("Arreglo unidimensional con random: ", arreglo_uni)
if np.isin(ingrese_numero,arreglo_uni):
  print(f"El número {ingrese_numero} está en el arreglo.")
else:
  print(f"El número {ingrese_numero} no está en el arreglo.")

#Ejercicio 2:
import numpy as np

def obtener_numero_entero(mensaje):
    while True:
        try:
            numero = int(input(mensaje))
            if 3 <= numero <= 6:
                return numero
            else:
                print("Número fuera del rango permitido.")
        except ValueError:
            print("Por favor, ingrese un número entero.")

num_entero1 = obtener_numero_entero("Ingrese primer número entero entre 3 y 6: ")
num_entero2 = obtener_numero_entero("Ingrese segundo número entero entre 3 y 6: ")

# Crear una matriz bidimensional con las dimensiones ingresadas y números enteros
matriz = np.random.randint(0, 101, size=(num_entero1, num_entero2))  # Aquí puedes ajustar el rango si es necesario

# Mostrar la matriz poblada
print("Arreglo poblado:")
print(matriz)

# Calcular y mostrar la suma por filas
suma_filas = np.sum(matriz, axis=1)
print("Suma por filas:")
print(suma_filas)

# Calcular y mostrar el promedio por columnas
promedio_columnas = np.mean(matriz, axis=0)
print("Promedio por columnas:")
print(promedio_columnas)

#Ejercicio 3:
import math # Importar el módulo math para usar funciones matemáticas avanzadas

def calcular_area_circulo(radio): # Definir una función para calcular el área de un círculo
    return math.pi * radio ** 2

def calcular_perimetro_cuadrado(lado): # Definir una función para calcular el perímetro de un cuadrado
    return 4 * lado

# Bucle principal del programa
while True:
    # Mostrar el menú al usuario
    print("Menú:")
    print("1. Calcular área de un círculo")
    print("2. Calcular perímetro de un cuadrado")
    print("3. Salir")

    # Solicitar al usuario que ingrese una opción
    opcion = input("Ingrese el número de opción: ")

    if opcion == "1":
        # Calcular el área de un círculo
        radio = float(input("Ingrese el radio del círculo: "))
        area = calcular_area_circulo(radio)
        print(f"El área del círculo con radio {radio} es: {area:.2f}")
    elif opcion == "2":
        # Calcular el perímetro de un cuadrado
        lado = float(input("Ingrese el lado del cuadrado: "))
        perimetro = calcular_perimetro_cuadrado(lado)
        print(f"El perímetro del cuadrado con lado {lado} es: {perimetro:.2f}")
    elif opcion == "3":
        # Salir del programa
        print("Saliendo del programa...")
        break
    else:
        # Opción inválida
        print("Opción inválida. Por favor, ingrese una opción válida.")

#Ejercicio 4:
def calcular_total(cantidad_espresso, cantidad_capuchino, cantidad_latte, cantidad_moca):
    precio_espresso = 1500
    precio_capuchino = 1800
    precio_latte = 1600
    precio_moca = 1700

    total_sin_descuento = (cantidad_espresso * precio_espresso) + (cantidad_capuchino * precio_capuchino) + (cantidad_latte * precio_latte) + (cantidad_moca * precio_moca)

    if total_sin_descuento >= 3000:
        total_con_descuento = total_sin_descuento * 0.9
        return total_con_descuento
    else:
        return total_sin_descuento

while True:
    print("Bienvenido a la cafetería. Menú de opciones:")
    print("1. Espresso")
    print("2. Capuchino")
    print("3. Latte")
    print("4. Moca")
    print("5. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        cantidad_espresso = int(input("Ingrese la cantidad de Espressos que desea: "))
        total_a_pagar = calcular_total(cantidad_espresso, 0, 0, 0)
        print(f"Total a pagar: ${total_a_pagar:.2f}")
    elif opcion == "2":
        cantidad_capuchino = int(input("Ingrese la cantidad de Capuchinos que desea: "))
        total_a_pagar = calcular_total(0, cantidad_capuchino, 0, 0)
        print(f"Total a pagar: ${total_a_pagar:.2f}")
    elif opcion == "3":
        cantidad_latte = int(input("Ingrese la cantidad de Lattes que desea: "))
        total_a_pagar = calcular_total(0, 0, cantidad_latte, 0)
        print(f"Total a pagar: ${total_a_pagar:.2f}")
    elif opcion == "4":
        cantidad_moca = int(input("Ingrese la cantidad de Mocas que desea: "))
        total_a_pagar = calcular_total(0, 0, 0, cantidad_moca)
        print(f"Total a pagar: ${total_a_pagar:.2f}")
    elif opcion == "5":
        print("Gracias por su visita. ¡Hasta luego!")
        break
    else:
        print("Opción no válida. Por favor, seleccione una opción válida.")